from __future__ import annotations

CONF_API_KEY = "api_key"
CONF_APIKEY = "apikey"
CONF_DEPARTURES = "departures"
CONF_ENTITY_NAMESPACE = "entity_namespace"
CONF_FEED_ID = "feed_id"
CONF_HEADERS = "headers"
CONF_ROUTE = "route"
CONF_STATIC_SCHEDULE_URL = "static_schedule_url"
CONF_STOP_ID = "stopid"
CONF_STOP_ARRIVALS_URL_TEMPLATE = "stop_arrivals_url_template"
CONF_TRANSIT_API_KEY = "transit_api_key"
CONF_TRANSIT_GLOBAL_STOP_ID = "transit_global_stop_id"
CONF_TRANSIT_ROUTE = "transit_route"
CONF_TRIP_UPDATE_URL = "trip_update_url"
CONF_VEHICLE_POSITION_URL = "vehicle_position_url"
CONF_X_API_KEY = "x_api_key"

DEFAULT_NAME = "Next Bus"
DEFAULT_TITLE = "GTFS-Realtime"
DOMAIN = "gtfs_rt"
ICON = "mdi:bus"
REQUEST_TIMEOUT = 30
TRANSIT_API_STOP_DEPARTURES_URL = "https://external.transitapp.com/v3/public/stop_departures"
TIME_STR_FORMAT = "%H:%M"
